import { Memo, MemoResult } from "./types";

const bullets = (items: string[]) => items.map((i) => `- ${i}`).join("\n");

/** Render a memo as a clean Markdown document for export / clipboard. */
export function memoToMarkdown(result: MemoResult, brandTitle: string): string {
  const { memo, site, generatedAt } = result;
  const m: Memo = memo;
  const date = new Date(generatedAt).toLocaleString();

  return `# Investment Memo — ${m.companySnapshot.name}

> Generated by ${brandTitle} · ${site.url} · ${date}

## Company Snapshot
- **Name:** ${m.companySnapshot.name}
- **Description:** ${m.companySnapshot.oneLiner}
- **Industry:** ${m.companySnapshot.industry}
- **Business model:** ${m.companySnapshot.businessModel}

## Problem
${m.problem.statement}

**Why it matters:** ${m.problem.importance}

## Product
**Core product:** ${m.product.core}

**Key features:**
${bullets(m.product.keyFeatures)}

**Differentiation:** ${m.product.differentiation}

## Market Opportunity
**Category:** ${m.market.category}

**Trends:**
${bullets(m.market.trends)}

**Adoption drivers:**
${bullets(m.market.adoptionDrivers)}

## Competitive Landscape
**Likely competitors:**
${bullets(m.competition.competitors)}

**Competitive advantages:**
${bullets(m.competition.advantages)}

**Potential weaknesses:**
${bullets(m.competition.weaknesses)}

## Team Signals
**Hiring activity:** ${m.team.hiringActivity}

**Growth indicators:**
${bullets(m.team.growthIndicators)}

**Organizational strengths:**
${bullets(m.team.strengths)}

## Bull Case
${bullets(m.bullCase)}

## Bear Case
**Top risks:**
${bullets(m.bearCase.risks)}

**Competitive threats:**
${bullets(m.bearCase.competitiveThreats)}

**Execution risks:**
${bullets(m.bearCase.executionRisks)}

## Investment Thesis
${m.investmentThesis}

## Recommendation
**${m.recommendation}** · Confidence ${m.confidenceScore}/100
`;
}
